Fix potential shortcut bug
dfmeta/devforumplus pull request #34
Opened 2021-01-31 15:53 UTC by brokenVectors

Fixed potential shortcut bug where shorter shortcuts containing the same characters as others would override them(e.g: !!LUA vs !!LUAU)

User is required to press space after entering the shortcut to replace it with desired text

2021-01-31 15:57 UTC, brokenVectors commented
I see that !!LUAU has already been replaced with !!VMLUAU, but that's pretty long and hacky in my opinion.

2021-01-31 16:13 UTC, FxllenCode approved these changes
Much better than !!VMLUAU. Simple but better for UX than having to type that.

2021-02-01 05:37 UTC, posatta requested changes
Add the space to the regex pattern, not just the replacement text

2021-02-01 05:39 UTC, posatta approved these changes

2021-02-01 05:43 UTC, posatta approved these changes
Should be good, but @zapacni or @FxllenCode should review again to make sure my code works fine

2021-02-01 05:46 UTC, zapacni approved these changes
Seems like a great QOL feature, this would also remove any conflict with templates that have the same start (e.g !!LUA vs !!LUAU, the composer won't be filled with the former)

2021-02-01 13:41 UTC, FxllenCode approved these changes
Still works as intended and does a great job at preventing future conflicts.

2021-02-01 14:57 UTC, merged